export const FETCH_FILTER_REQUEST = 'FETCH_FILTER_REQUEST';
export const FETCH_FILTER_SUCCESS = 'FETCH_FILTER_SUCCESS';
export const SIZE_FILTER_VALUE = 'SIZE_FILTER_VALUE';
export const STYLE_FILTER_VALUE = 'STYLE_FILTER_VALUE';
export const COLOR_FILTER_VALUE = 'COLOR_FILTER_VALUE';
export const CLEAR_FILTER_VALUE = 'CLEAR_FILTER_VALUE';
