export const FETCH_PICTURE_REQUEST = 'FETCH_PICTURE_REQUEST';
export const FETCH_PICTURE_SUCCESS = 'FETCH_PICTURE_SUCCESS';
export const SET_UPLOAD_FILE = 'SET_UPLOAD_FILE';
export const SUCCESS_UPLOAD_FILE = 'SUCCESS_UPLOAD_FILE';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';